---
- name: copy install-config.yaml into install_dir
  ansible.builtin.template:
    src: "{{ role_path }}/templates/install-config.yaml.j2"
    dest: "{{ install_dir.path }}/install-config.yaml"

- name: run IPI installer
  command: "{{ bin_dir }}/openshift-install create cluster --dir={{ install_dir.path }}"
  register: cluster_deploy
...