---
- include_role:
    name: admin_get_service_account_token
  vars:
    cluster_address: "{{ hub_address }}"

- name: Get API tokenfile
  include_vars: "{{ acm_service_account_tokenfile }}"

- name: Create namespace for managed cluster
  kubernetes.core.k8s:
    host: "https://api.{{ hub_address }}:6443"
    api_key: "{{ vars[acm_token_var] }}"
    validate_certs: no
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ cluster_name }}"

- name: Create ManagedCluster custom resource
  kubernetes.core.k8s:
    host: "https://api.{{ hub_address }}:6443"
    api_key: "{{ vars[acm_token_var] }}"
    validate_certs: no
    state: "{{ state }}"
    definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ cluster_name }}"
        labels:
          cloud: auto-detect
          vendor: auto-detect
      spec:
        hubAcceptsClient: true

- name: Create Auto Import Secret
  kubernetes.core.k8s:
    host: "https://api.{{ hub_address }}:6443"
    api_key: "{{ vars[acm_token_var] }}"
    validate_certs: no
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: auto-import-secret
        namespace: "{{ cluster_name }}"
      stringData:
        autoImportRetry: "5"
        token: "{{ managed_cluster_token }}"
        server: "https://api.{{ cluster_name }}.{{ base_domain }}:6443"
      type: Opaque

#  oc get secret <cluster_name>-import -n <cluster_name> -o jsonpath={.data.crds\\.yaml} | base64 --decode > klusterlet-crd.yaml
#  oc get secret <cluster_name>-import -n <cluster_name> -o jsonpath={.data.import\\.yaml} | base64 --decode > import.yaml

- name: Get Cluster Import Secret
  kubernetes.core.k8s_info:
    host: "https://api.{{ hub_address }}:6443"
    api_key: "{{ vars[acm_token_var] }}"
    api_version: v1
    kind: Secret
    name: "{{ cluster_name }}-import"
    namespace: "{{ cluster_name }}"
  register: import_secret

- debug:
    msg: "{{ import_secret.data.crds }}"

- debug:
    msg: "{{ import_secret.data.import }}"

- name: Create KlusterletAddonConfig custom resource
  kubernetes.core.k8s:
    host: "https://api.{{ hub_address }}:6443"
    api_key: "{{ vars[acm_token_var] }}"
    validate_certs: no
    state: "{{ state }}"
    definition:
      apiVersion: agent.open-cluster-management.io/v1
      kind: KlusterletAddonConfig
      metadata:
        name: "{{ cluster_name }}"
        namespace: "{{ cluster_name }}"
      spec:
        applicationManager:
          enabled: true
        certPolicyController:
          enabled: true
        iamPolicyController:
          enabled: true
        policyController:
          enabled: true
        searchCollector:
          enabled: true

- name: Wait for ManagedCluster to become available
  kubernetes.core.k8s_info:
    host: "https://api.{{ hub_address }}:6443"
    api_key: "{{ vars[acm_token_var] }}"
    validate_certs: no
    kind: ManagedCluster
    name: "{{ cluster_name }}"
    wait: true
    wait_condition:
      reason: ManagedClusterAvailable
      type: ManagedClusterConditionAvailable
    wait_sleep: 1
...