kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv
#  storageClassName: gp3-csi
  volumeMode: Filesystem
