---
- name: "OpenShift CLI login"
  shell: "oc login -u {{ admin_user }} -p {{ admin_password }} https://api.{{ cluster_address }}:6443 --insecure-skip-tls-verify"

- name: Get ServiceAccount Secret
  k8s_info:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    kind: Secret
    namespace: "{{ acm_service_account_namespace }}"
  register: sa_secrets
  when: state == "present"

- name: Get Service Account token
  set_fact:
    sa_token: "{{ item.data.token | b64decode }}"
  with_items: "{{ sa_secrets.resources }}"
  when: (state == "present") and
    (item.metadata.name.startswith(acm_service_account_name + "-token-"))
  loop_control:
    label: "{{ item.metadata.name }}"

- name: Create token file
  copy:
    dest: "{{ acm_service_account_tokenfile }}"
    content: "{{ acm_token_var }}: {{ sa_token }}"
  when: state == "present"
...