---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/node-selector: 'cluster.ocs.openshift.io/openshift-storage='
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage