---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  placement:
    all:
      tolerations:
        - key: node.ocs.openshift.io/storage
          effect: NoSchedule
          value: "true"
    mds:
      tolerations:
        - key: node.ocs.openshift.io/storage
          effect: NoSchedule
          value: "true"
    noobaa-core:
      tolerations:
        - key: node.ocs.openshift.io/storage
          effect: NoSchedule
          value: "true"
    rgw:
      tolerations:
        - key: node.ocs.openshift.io/storage
          effect: NoSchedule
          value: "true"
  storageDeviceSets:
    - config: {}
      count: 1
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1"
          storageClassName: local-block
          volumeMode: Block
        status: {}
      name: ocs-deviceset-local-block
      placement: {}
      preparePlacement: {}
      replica: 4
      resources:
        limits:
          cpu: '2'
          memory: 5Gi
        requests:
          cpu: '1'
          memory: 5Gi
  encryption:
    kms: {}
  mirroring: {}
  monDataDirHostPath: /var/lib/rook
  resources:
    mds:
      limits:
        cpu: '3'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 8Gi
    rgw:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 4Gi
  managedResources:
    cephObjectStoreUsers: {}
    cephCluster: {}
    cephBlockPools: {}
    cephNonResilientPools: {}
    cephObjectStores: {}
    cephFilesystems: {}
    cephRBDMirror: {}
    cephToolbox: {}
    cephDashboard: {}
    cephConfig: {}
  arbiter: {}
  network:
    connections:
      encryption: {}
    multiClusterService: {}
  nodeTopologies: {}
  externalStorage: {}
  flexibleScaling: true
#  multiCloudGateway:
#    dbStorageClassName: gp3-csi
#    reconcileStrategy: standalone