---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  placement:
    all:
      tolerations:
        - key: node.ocs.openshift.io/storage
          effect: NoSchedule
          value: "true"
    mds:
      tolerations:
        - key: node.ocs.openshift.io/storage
          effect: NoSchedule
          value: "true"
    noobaa-core:
      tolerations:
        - key: node.ocs.openshift.io/storage
          effect: NoSchedule
          value: "true"
    rgw:
      tolerations:
        - key: node.ocs.openshift.io/storage
          effect: NoSchedule
          value: "true"
  resourceProfile: balanced
  storageDeviceSets:
    - config: {}
      count: 1
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1"
          storageClassName: local-block
          volumeMode: Block
        status: {}
      name: ocs-deviceset-local-block
      placement: {}
      preparePlacement: {}
      replica: 4
      resources: {}
  encryption:
    kms: {}
  mirroring: {}
  monDataDirHostPath: /var/lib/rook
  managedResources:
    cephBlockPools: {}
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephNonResilientPools:
      count: 1
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephRBDMirror:
      daemonCount: 1
    cephToolbox:
      reconcileStrategy: init
  enableCephTools: true
  arbiter: {}
  network:
    connections:
      encryption: {}
    multiClusterService: {}
  nodeTopologies: {}
  externalStorage: {}
  flexibleScaling: true
#  multiCloudGateway:
#    dbStorageClassName: gp3-csi
#    reconcileStrategy: standalone