---
- name: Create ACS Backup CronJob
  gather_facts: false
  hosts: localhost
#  vars_prompt:
#    # Prompt for cluster name
#    - name: ocp_cluster_address
#      prompt: Enter OCP Hub Cluster Address (e.g. clustername.domain.com)
#      private: no
#      confirm: no
#    # Prompt for cluster-admin username
#    - name: cluster_admin_user
#      prompt: Enter cluster-admin user
#      private: no
#      confirm: no
#    # Prompt for cluster-admin password
#    - name: cluster_admin_password
#      prompt: Enter cluster-admin password
#      private: yes
#      confirm: no
#    # Prompt for ACS API token
#    - name: acs_api_token
#      prompt: Enter ACS API token
#      private: yes
#      confirm: no
  tasks:
    - include_role:
        name: admin_create_cluster_admin_service_account
      vars:
        cluster_address: "{{ ocp_cluster_address }}"
        admin_user: "{{ cluster_admin_user }}"
        admin_password: "{{ cluster_admin_password }}"

    - include_role:
        name: create_acs_backup_cronjob
      vars:
        cluster_address: "{{ ocp_cluster_address }}"
        admin_user: "{{ cluster_admin_user }}"
        admin_password: "{{ cluster_admin_password }}"
        b64_acs_api_token: "{{ acs_api_token | b64encode }}"
...