---
- name: Install ACS via ACM Policy
  gather_facts: false
  hosts: localhost
#  vars_prompt:
#    # Prompt for cluster name
#    - name: ocp_cluster_address
#      prompt: Enter OCP Cluster Address (e.g. clustername.domain.com)
#      private: no
#      confirm: no
#    # Prompt for cluster-admin username
#    - name: cluster_admin_user
#      prompt: Enter cluster-admin user
#      private: no
#      confirm: no
#    # Prompt for cluster-admin password
#    - name: cluster_admin_password
#      prompt: Enter cluster-admin password
#      private: yes
#      confirm: no
  tasks:
    - name: TODO REMOVE temp for testing
      set_fact:
        ocp_cluster_address: acm-hub.sandbox3005.opentlc.com
        cluster_admin_user: kubeadmin
        cluster_admin_password: cIYBh-aTR5M-KQI4Z-EW5q4

    - name: "OpenShift CLI login"
      shell: "oc login -u {{ cluster_admin_user }} -p {{ cluster_admin_password }} https://api.{{ ocp_cluster_address }}:6443 --insecure-skip-tls-verify"

    - include_role:
        name: admin_create_service_account
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_acs_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"
...