---
- name: Provision cluster on Nutanix and import as ACM Managed Cluster
  gather_facts: false
  hosts: localhost
#  vars_prompt:
#    # Prompt for hub cluster address
#    - name: ocp_cluster_address
#      prompt: Enter ACM Hub Cluster Address
#      private: no
#      confirm: no
#    # Prompt for hub cluster-admin username
#    - name: cluster_admin_user
#      prompt: Enter ACM Hub cluster-admin user
#      private: no
#      confirm: no
#    # Prompt for hub cluster-admin password
#    - name: cluster_admin_password
#      prompt: Enter ACM Hub cluster-admin password
#      private: yes
#      confirm: no
#    # Prompt for cluster name
#    - name: managed_cluster_name
#      prompt: Enter Managed Cluster Name
#      private: no
#      confirm: no
#    # Prompt for base domain
#    - name: managed_cluster_base_domain
#      prompt: Enter Base Domain for Managed Cluster
#      private: no
#      confirm: no
  tasks:
    - name: Create temporary directory for template files
      tempfile:
        state: directory
        suffix: tmp
      register: tmp_dir

    - set_fact:
        working_dir: "{{ tmp_dir.path }}"

    - name: create install_dir to work in
      ansible.builtin.file:
        state: directory
        path: "{{ working_dir }}/install/{{ managed_cluster_name }}"
      register: install_dir

    - name: print install_dir location for admin
      ansible.builtin.debug:
        msg: "The working directory location is {{ install_dir.path }}"

    - include_role:
        name: provision_managed_cluster_nutanix
      vars:
        cluster_name: "{{ managed_cluster_name }}"
        base_domain: "{{ managed_cluster_base_domain }}"

    - name: Set kubeconfig fact
      set_fact:
        kubeconfig: "{{ working_dir }}/install/{{ managed_cluster_name }}/auth/kubeconfig"

    - name: Get kubeadmin password
      set_fact:
        kubeadmin_pass: "{{ lookup('file','{{ working_dir }}/install/{{ managed_cluster_name }}/auth/kubeadmin-password') }}"

    - include_role:
        name: import_managed_cluster
      vars:
        cluster_name: "{{ managed_cluster_name }}"
        base_domain: "{{ managed_cluster_base_domain }}"
        hub_address: "{{ ocp_cluster_address }}"
        hub_username: "{{ cluster_admin_user }}"
        hub_password: "{{ cluster_admin_password }}"
        managed_cluster_username: kubeadmin
        managed_cluster_password: "{{ kubeadmin_pass }}"
        kubeconfig_file: "{{ kubeconfig }}"
...